# composite tasks
[tasks.clean]
dependencies = ["clean-cargo", "clean-libpcap", "clean-tcpdump", "clean-build-dir"]

[tasks.build]
dependencies = ["clean", "copy-project-to-build", "build-libpcap", "build-tcpdump"]

# clean up tasks
[tasks.clean-cargo]
command = "cargo"
args = ["clean"]

[tasks.clean-libpcap]
command = "make"
args = ["-C", "libpcap", "clean"]

[tasks.clean-tcpdump]
command = "make"
args = ["-C", "tcpdump", "clean"]

[tasks.clean-build-dir]
command = "rm"
args = ["-rf", "build/"]

# build tasks
[tasks.copy-project-to-build]
script = """
mkdir -p build/
"""

[tasks.build-libpcap]
cwd = "libpcap"
script = """
./configure --enable-shared=no --prefix="${CARGO_MAKE_WORKING_DIRECTORY}/../build/"
make
make install
"""

[tasks.build-tcpdump]
cwd = "tcpdump"
script = """
CPPFLAGS=-I"${CARGO_MAKE_WORKING_DIRECTORY}/../build/include/" LDFLAGS="-L${CARGO_MAKE_WORKING_DIRECTORY}/../build/lib/" ./configure --prefix="${CARGO_MAKE_WORKING_DIRECTORY}/../build/"
make
make install
"""

