[tasks.clean]
dependencies = ["cargo-clean", "afl-clean", "clean-xpdf"]

[tasks.afl-clean]
script = '''
rm -rf .cur_input* timeouts
'''

[tasks.clean-xpdf]
cwd = "xpdf"
script = """
make --silent clean
rm -rf built-with-* ../build/* install
"""

[tasks.cargo-clean]
command = "cargo"
args = ["clean"]

[tasks.rebuild]
dependencies = ["afl-clean", "clean-xpdf", "build-xpdf", "build-fuzzer"]

[tasks.build-xpdf]
cwd = "xpdf"
script = """
export LLVM_CONFIG=llvm-config-15
CC=afl-clang-fast CXX=afl-clang-fast++ ./configure --prefix=./install
make
make install
"""

[tasks.build-fuzzer]
script = """
cargo build --release
"""
